### PR TITLE
Template security.conf in Debian

### PR DESCRIPTION
**Pull request by alxwr**
(including a call to optional per-OS templates)

Solves https://github.com/saltstack-formulas/apache-formula/issues/153

**Summary of Changes**
 * `manage_security.sls`
   - Debian: Replaced `file.blockreplace` with `file.managed` plus a template
   - FreeBSD: no changes (just reused that minimalistic template)

**Testing**
 - Tested on OS (FreeBSD and Debian)

### CODE REVIEW

**Comment by alxwr** [comment]
The absence of this patch just brought down an Apache instance of mine. :-(
Can we please merge?

**Comment by aboe76** [comment]
@alxwr is this backwards compatible or do we need to manipulate pillar.example?

**Comment by alxwr** [comment]
@aboe76 This change was backwards compatible.

**Comment by aboe76** [comment]
@alxwr thanks for the clarification.

**Pull request merged**
