### PR TITLE
fix(mod_mpm): cast to int to avoid Jinja type mismatch error

### PR DESCRIPTION
**Pull request by dimitry-unified-streaming**
This fixes the following error when Jinja tries to process
`mpm_prefork.conf.jinja`, when it processes the `max_request_workers`
comparison:

```
Unable to manage file: Jinja error: '>=' not supported between instances of 'str' and 'int'
[...]
<IfModule mpm_prefork_module>
  StartServers {{ mpm_param['start_servers'] | d('5') }}
  MaxRequestWorkers {{ mpm_param['max_request_workers'] | d('150') }}
{%- if mpm_param['max_request_workers'] | d('150') >= 256 %}    <======================
  ServerLimit {{ mpm_param['max_request_workers'] | d('150') }}
{%- endif %}
  MinSpareServers {{ mpm_param['min_spare_servers'] | d('5') }}
  MaxSpareServers {{ mpm_param['max_spare_servers'] | d('10') }}
  MaxConnectionsPerChild {{ mpm_param['max_connections_per_child'] | d('0') }}
```

Add a filter that converts the value to an int first.

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
Thanks for this @dimitry-unified-streaming.  So that we can keep things consistent, would you mind working through the other occurrences of this, starting from this search?

* https://github.com/saltstack-formulas/apache-formula/search?q=max_request_workers&unscoped_q=max_request_workers

**Comment by dimitry-unified-streaming** [comment]
> Thanks for this @dimitry-unified-streaming. So that we can keep things consistent, would you mind working through the other occurrences of this, starting from this search?
> 
>     * https://github.com/saltstack-formulas/apache-formula/search?q=max_request_workers&unscoped_q=max_request_workers

I could do that, but since none of the other uses of `max_request_workers` are in a comparison, it does not really serve any purpose. (Well, maybe if Jinja is then validating that the setting is an integer; however, the documentation says that if it is not valid, it will return 0.)

**Comment by myii** [comment]
@dimitry-unified-streaming There is this one:

https://github.com/saltstack-formulas/apache-formula/blob/7bac5c7c30f49e9b326bc2bc6ea2578b090e25a2/apache/files/RedHat/conf.modules.d/00-mpm.conf.jinja#L24

**Comment by myii** [comment]
@dimitry-unified-streaming Thanks for the update.

**Pull request merged**
