### PR TITLE
FreeBSD support

### PR DESCRIPTION
**Pull request by alxwr**
**Summary of Changes**
- Added basic FreeBSD support
- global DocumentRoot
- envvars
- mod_perl2
- mod_proxy
- mod_php5
- mod_ssl
- mod_suexec
- mod_rewrite
- apache.global for Debian and FreeBSD

**Testing**
- tested on OS

### CODE REVIEW

**Comment by alxwr** [comment]
Added:
envvars
mod_perl2
mod_proxy
mod_rewrite
mod_suexec

**Comment by alxwr** [comment]
Added:
- apache.mod_proxy_http

**Comment by alxwr** [comment]
Added:
- apache.mod_cgi

**Comment by alxwr** [comment]
@gravyboat @aboe76
Do you see any problem with adding FreeBSD support?
Tested it for about three months on Debian, Ubuntu and FreeBSD. The changes that could affect Debian are minimal.

I'm waiting at least until the end of this week for your reply, before I'll merge.

Thanks,
Alex

**Comment by gravyboat** [comment]
@alxwr Nope! I stepped down from this org a while ago so I can't do merges any more. @whiteinge could you please merge this in?

**Comment by alxwr** [comment]
@gravyboat
I've got push access myself. Just didn't want to step on anyones toes on a rather important formula. :-)
Thanks!

CC @whiteinge

**Pull request merged**
