### PR TITLE
corrected the key to match the pillar.example

### PR DESCRIPTION
**Pull request by papoyan**

### CODE REVIEW

**Comment by gravyboat** [comment]
Thanks!

**Comment by gravyboat** [comment]
Sorry I had to revert this, where is the lookup present inside the pillar.example?

**Comment by papoyan** [comment]
That's the issue, that lookup is not present in the pillar.example, however map.jinja is set to the following 
merge=salt['pillar.get']('apache:lookup')

**Comment by iamseth** [comment]
@gravyboat 

The pillar.example doesn't use lookup, that's the issue.

The pillar.example says that I can change the value of 'apache.server' by setting 'apache.server' but map.jinja file uses the key 'apache.lookup.server'.

If I wanted to change the value of 'server', 'logdir', or 'confdir', I'd need to use the lookup key in my Pillar file. Setting 'apache.server' would not work.

Hope that makes sense :)

**Comment by gravyboat** [comment]
@papoyan @iamseth Yes this makes sense to me. Maybe I explained myself poorly, but the pillar.example (as you said) does not use lookup, so the pillar.example needs to be updated to match this change.

**Comment by iamseth** [comment]
Either can be updated I suppose. I would say that since this is already in the wild that changing the example pillar to reflect map.jinja is the safer option to avoid breaking existing installations but they probably should match.

**Comment by gravyboat** [comment]
I'm fine with changing the map.jinja to use the lookup (and it should) but the PR for that needs to include an update pillar.example.

**Comment by iamseth** [comment]
"I'm fine with changing the map.jinja to use the lookup "

OK, I think we're missing each other a bit. It already DOES use lookup. The current pillar.example in master is NOT using lookup. So they don't currently match. A correct change would alter one to match the other. This pull request made them match but I see the benefit of changing pillar and not map.jinja.

See this file which does NOT mention lookup

https://github.com/saltstack-formulas/apache-formula/blob/master/pillar.example

And then this file which merges pillar USING lookup.

https://github.com/saltstack-formulas/apache-formula/blob/master/apache/map.jinja

So only one should change to match the other. Not both.

**Comment by gravyboat** [comment]
@iamseth You're right, my brain was messing up the PR it seems where I thought we were ADDING lookup to the map.jinja, not removing it, thus the confusion. Jeez I don't know how I looked at that 3 times and still went 'nope adding lookup is not acceptable without a pillar update'. @papoyan please PR again, I'll merge that one, sorry for the confusion guys.

**Comment by iamseth** [comment]
Heh, it's cool. I wasted most of yesterday because I wasn't compensating for indexing an array by 1 instead of 0 :)

I think this PR was probably good to be reverted only because it's safer to change the documentation (pillar.example) and not the code. It's possible that users are already using this formula and overriding default values via Pillar. The example pillar would impact new users.

I think it's better to impact new users than existing. It also seems like convention to use lookup on several formulas under https://github.com/saltstack-formulas so keeping lookup and updating doc to reflect actual code seems logical. Just my $.02.

**Comment by gravyboat** [comment]
Yeah the lookup is pretty standard throughout the formula system. I'm not sure why the apache pillar was never updated even though the map was. @papoyan any concerns you have over modifying it the other way (pillar.example instead of map.jinja)?

**Pull request merged**
