### PR TITLE
fix(package): avoid unnecessary state change

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

This PR stops an unnecessary state from being triggered by adding `on_fail` condition.

Without this PR this happens:
```
         ID: apache-package-install-deps-pkg-installed
    Function: pkg.installed
        Name: libapache2-mod-security2
      Result: True
     Comment: All specified packages are already installed
     Started: 23:51:24.684213
    Duration: 7.745 ms
     Changes:
----------
          ID: apache-package-install-deps-pkg-installed
    Function: cmd.run
        Name: apt install libapache2-mod-security2 || true
      Result: True
     Comment: Command "apt install libapache2-mod-security2 || true" run
     Started: 23:51:24.700641
    Duration: 657.234 ms
     Changes:
              ----------
              pid:
                  26533
              retcode:
                  0
              stderr:

                  WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
              stdout:
                  Reading package lists...
                  Building dependency tree...
                  Reading state information...
                  libapache2-mod-security2 is already the newest version (2.9.2-1).
                  0 upgraded, 0 newly installed, 0 to remove and 33 not upgraded.
```
And rerun reports 1 changed state:
```
Succeeded: 28 (changed=1)
Failed:     0
-------------
Total states run:     
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
@SuperTux88 could you review this PR please?

**Review by SuperTux88 — CHANGES_REQUESTED** [review]
I would put an `if` around the `cmd.run` to check if `libapache2-mod-security2` is included in `apache.pkg.deps` and don't run it otherwise.

Also `pkg.installed` doesn't fail for me, so I don't know what you actually try to fix here. But you probably want to at least add a `-y` parameter to `apt install`, because without it, it just hangs there and asks for confirmation.

**Comment by noelmcloughlin** [comment]
Thanks, I think we can remove that state. I remember having weirdness running VM on VirtualBox on Windows. This was probably a symptom. Eventually, I switched to Hyper-V and VM weirdness was gone (i.e. faulty network virtualization). Commit updated.

**Review by SuperTux88 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
