### PR TITLE
ensure php5 module is enabled on openSUSE / SLE

### PR DESCRIPTION
**Pull request by fcrozat**
**Summary of Changes**
 * Issue summary 
 - Indented line 1
 - Indented line 2
**Testing**
 - Ran `make`
 - Tested in Vagrant
 - Tested on OS

### CODE REVIEW

**Comment by javierbertoli** [comment]
Shouldn't this resource you're adding work the same on the other RedHat-based distros (fedora, centos, suse, redhat, etc.)? Maybe it can be extended adding these distros to the grain conditional?

**Comment by fcrozat** [comment]
suse isn't a RedHat-based distro, but I assume you mean RPM-based distro. Unfortunately, I don't use those, so I don't know how they are packaged.

**Comment by aboe76** [comment]
@fcrozat did os_family value came from Sles? or openSUSE?

**Comment by fcrozat** [comment]
@aboe76 it covers both SLES and all openSUSE (Leap and TW). And we have compatible packaging between the various distributions.

**Pull request merged**
