### PR TITLE
Applied workaround of https://github.com/saltstack-formulas/apache-formula/issues/153

### PR DESCRIPTION
**Pull request by kadogo**
I applied the workaround of https://github.com/saltstack-formulas/apache-formula/issues/153 because I have always the problem.

The saltstack ticket is already closed so I think it's better to have a workaround for the formula for now.

### CODE REVIEW

**Comment by aboe76** [comment]
https://github.com/saltstack/salt/pull/36273 has been merged so the workaround isn't needed any more,

Should I merge this and then fix the the workaround or can you make the pr without it?

**Comment by alxwr** [comment]
> Should I merge this and then fix the the workaround or can you make the pr without it?

@aboe76 
The workaround doesn't work any more :-) (At least in my tests the newline between the last line and the end-marker gets removed.)

Now this is needed to add the newline before the end-marker:

```yaml
apache_security-block:
  file.blockreplace:
    - name: /etc/apache2/conf-available/security.conf
[…]
    - context:
        append_newline: True
```

There’s another issue: It seems that the PR has been lost. `append_newline` can't be found in the current version of the docs: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html
(My 2016.11.3 installation doesn't have the code either.)

To be frank, the current way of managing `security.conf` seems a bit messy. Is there a reason why we append a block of values instead of replacing them where they are? Or why don't we just generate `security.conf` based on a template?

If there’s no problem with just using a template, I'd be happy to submit a PR.

@kadogo 
Do you consider the additional commits ready to be merged, or is this WIP?

**Comment by aboe76** [comment]
@alxwr The other additions looks ready for merging, I don't mind templating security.conf,
but I don't know what other people like...

**Comment by alxwr** [comment]
@aboe76 @kadogo 
> The other additions looks ready for merging, 
I took everything except for the workaround. Thank you for contributing!

>I don't mind templating security.conf, but I don't know what other people like...
I'll open an extra PR for that.

**Comment by alxwr** [comment]
Templating `security.conf`: #184

**Pull request closed without merging**
