### PR TITLE
refactor(formula): align to template-formula & improve ci

### LINKED ISSUE #79: Consistency: `state: enabled` and `enabled: true`.
Right now, there are 2 mechanisms to enable a site.

The current one, used by `apache.register_site` is the `state: enabled` attribute from the pillar `apache:register-site:$SITE`.

Another one which was introduced in @c195dce07c11f50d7914ecd324108fa95e70b3e5 uses the `enabled` attribute in `apache:sites:$SITE`.

I believe the latter approach is the better one, as `apache.register_site` is currently specific to `grains['os_family'] == 'Debian'`, so `apache.register_site` should be changed to use the other approach.
Otherwise there will be 2 keys to realize more or less the same mechanism which is incosistent and might cause confusion.

### PR DESCRIPTION
**Pull request by noelmcloughlin**
BREAKING CHANGE: Module .sls files are moved to /config/modules/ subdirectory.
template-formula alignment may introduce a breaking change. See README for states.

### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [x] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [x] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

YES
- moved modules SLS to config/modules/
- aligned to template-formula

### Related issues and/or pull requests

Includes #225 and #259
Fixes #79, #238, #258, #262, #265, #266 

### Describe the changes you're proposing

While using this formula I saw various issues and inconsistencies.  
This PR is an attempt to improve formula quality while keeping the same functionality.  
- Align structure with template-formula (state naming, requisites, structure).
- Expanded CI/CD coverage (platforms and pillar data)
- Move all module SLS files to a subdirectory
- Pass expanded set of use cases on CENT 6/7/8, OpenSuse Leap 15, Ubuntu 18, Debian 10, Windows/Cygwin, Amazon2.
- Fix #79, #238, #258, #262, #265, #266 

I'm sorry the PR is so big but there is no easy way to improve feature/test coverage without restructuring.
The CI/CD is passing for all platforms except:
- CentOS 6 (works for me in Vagrant, but not Travis)
- Archlinux (needs work)

Further work is required to address remaining open issues.  
There may be better ways of processing modules but this PR relies on the existing solutions.

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [x] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Added support for Archlinux (CI/CD) with HTTPS/SSL and modules.

**Comment by noelmcloughlin** [comment]
I discussed this PR with @myii and because it's too big to review I'll selfie-merge on the following basis:
1. firstly the commit message lists all breaking/unbreaking changes
2. The extended and improved CI/CD is passing
3. That I'll become code owner if necessary.

Pillar data is unchanged. The primary change is state-names were refactored as part of the alignment with template-formula.

**Comment by myii** [comment]
@noelmcloughlin Nice work, the breaking changes listed in the changelog make things so much easier to follow -- appreciate it.

**Comment by myii** [comment]
Just a little note for posterity.

I wasn't able to `git pull` these changes without manual operation (but I do use my formulas' repos in non-standard ways to most people).  I was getting this error:

```bash
error: Updating the following directories would lose untracked files in them:
        apache/vhosts
```

Was able to check the problem using `git clean` in dry-run mode:

```bash
$   git clean -xdfn
...
Would remove apache/vhosts/.cleanup.sls.un~
Would remove apache/vhosts/.minimal.tmpl.un~
Would remove apache/vhosts/.proxy.tmpl.un~
Would remove apache/vhosts/.redirect.tmpl.un~
Would remove apache/vhosts/.standard.tmpl.un~
...
```

* https://stackoverflow.com/a/46140753

So the main point is that making modifications to the directory structure could lead to issues with certain files being present in the directories that are being moved (i.e. those covered by `.gitignore`).

This is more so a point of awareness, there's not much we could do about this.

**Comment by myii** [comment]
Standardised this implementation with 7dc0ece4f5d1659be266f82f3dfe05a82833f41c.

**Pull request merged**
