### PR TITLE
Updated Travis/Kitchen tests

### PR DESCRIPTION
**Pull request by noelmcloughlin**
**Summary of Changes**
 * This PR updates travis/kitchen tests

**Testing**
 - Passed in Docker (Ubuntu/Centos/Debian9) on travis-ci

**Prerequisites**
  - Enable saltstack-formulas/apache in travis-ci

### CODE REVIEW

**Comment by alxwr** [comment]
@noelmcloughlin 
> Enable saltstack-formulas/apache in travis-ci

Is this something I need to do before merging the PR? (Because I've got no clue how to do this. :-)

**Comment by noelmcloughlin** [comment]
@alxwr Thanks, but I'm not sure either.  
@gtmanfred do you know how to enable this formula in travis-ci?

**Comment by gtmanfred** [comment]
Should be all set to go!
Daniel

**Comment by aboe76** [comment]
@gtmanfred thanks for enabling travis.

**Pull request merged**
