### PR TITLE
add a boolean to a site configuration to enable or disable it

### PR DESCRIPTION
**Pull request by Wenzel**
This introduces a new boolean attribute for a given site in the pillar : `enabled`
It will `a2ensite` or `a2dissite` the site according to the attribute's value.

This way you can for example disable sites that are enabled by default after the installation of apache :
~~~
apache:
   sites:
      000-default:
          enabled: False

     default-ssl:
         enabled: False
~~~

### CODE REVIEW

**Comment by gravyboat** [comment]
Good stuff, thanks!

**Comment by Tangresh** [comment]
Does this mean all existing configurations break, because the default is now to disable a configured site?

**Comment by Wenzel** [comment]
@Tangresh that's a good remark.
I didn't notice it when I made the PR, but if you have declared a site in the pillar without the `enabled` attribute set, this will be disabled.

So the solution might to change the line `33` in `apache/vhosts/standard.sls`
~~~
{% if site.get('enabled') %}
~~~

by this one

~~~
{% if site.get('enabled', True) %}
~~~

**Comment by Tangresh** [comment]
I made pull request #87 to change it.

**Pull request merged**
