### PR TITLE
fix #278 check if /etc/apache/sites-enabled exists before listing it

### LINKED ISSUE #278: [BUG] apache.vhost.cleanup fails if apache is not yet installed
### Formula commit hash / release tag

Using apache and apache.vhost.cleanup on a new machine.

The test https://github.com/saltstack-formulas/apache-formula/blob/master/apache/vhosts/cleanup.sls#L24 fails as apache may not yet be installed.

Using commit id 2417a75fe218bd04c719f8eb2e2a7e402a20928e 

### Versions reports (master & minion)

```
# salt -V
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.4 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-9-amd64
         system: Linux
        version: debian 10.4 
```
Same for master, syndic and minion

### Pillar / config used

apache role (in pillarstack) :
```
states:
  list:
    - apache.debian_full
    - apache.mod_geoip
    - apache.mod_ssl
    - apache.mod_remoteip
    - apache.mod_mpm
    - apache.config
    - apache.modules
    - apache.manage_security
    - apache.vhosts.standard
    - apache.vhosts.cleanup
```

---

### Describe the bug

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:apache.vhosts.cleanup' failed: Problem running salt function in Jinja template: A valid directory was not specified.; line 24

---
[...]
{% for id, site in salt['pillar.get']('apache:register-site', {}) %}
{%   do valid_sites.append('{}{}'.format(site.name, apache.confext)) %}
{% endfor %}


{% for filename in salt['file.readdir']('/etc/apache2/sites-enabled/') %}    <======================
{%   if filename not in valid_sites %}

a2dissite {{ filename }}:
  cmd.run:
    - onlyif: "test -L {{ dirpath }}/{{ filename }} || test -f {{ dirpath }}/{{ filename }}"
[...]
---
```

### Expected behaviour

cleanup should first test if the directory exists (or apache is installed), or fails silently if the directory is absent.

### Attempts to fix the bug

None

### PR DESCRIPTION
**Pull request by Yoda-BZH**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

Attempt at fixing #278 .
If apache is not yet installed, listing the directory `/etc/apache2/sites-enabled` should not be performed.

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

Fix #278 

### Describe the changes you're proposing

Added a check with `salt['file.directory_exists']('/etc/apache2/sites-enabled')` before listing the directory.
Plus, I used `dirpath` everywhere to avoid duplication of a fixed string.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

Thanks

### CODE REVIEW

**Comment by myii** [comment]
@Yoda-BZH Thanks for the original report and the proposed fix.  I'll try to look over this in the coming days if someone else doesn't do it.  Please feel free to ping me if you don't hear from me soon.

**Comment by Yoda-BZH** [comment]
@myii ping ? :)

**Comment by myii** [comment]
@Yoda-BZH Thanks for the ping.  We're short on maintainers these days.  I've saved/bookmarked this PR so it will be one of the first ones I look at when I get through some of the organisational tasks I've got in front of me regarding SaltStack Formulas.  I appreciate your patience.

**Comment by Yoda-BZH** [comment]
ok no problem :)

**Comment by myii** [comment]
@Yoda-BZH Apologies for the delay, merged after confirming the fix works locally with Kitchen.  Had to update the commit message to pass the `commitlint`:

```diff
-fix #278 check if /etc/apache/sites-enabled exists before listing it
+fix(vhosts/cleanup): check `sites-enabled` dir exists before listing it
```

**Comment by Yoda-BZH** [comment]
thank you !

**Pull request merged**
