### PR TITLE
Added Timeout and LimitRequestsFields to vhosts

### PR DESCRIPTION
**Pull request by opdude**

### CODE REVIEW

**Comment by gravyboat** [comment]
Are we missing stuff from your original PR: https://github.com/saltstack-formulas/apache-formula/pull/116/files or are these changes intended?

**Comment by babilen** [comment]
I think this PR might be due to me mentioning that it would be nice if the other PR could be rebased against master.

**Comment by opdude** [comment]
I split these changes into multiple PRs to be more clear about what each was for

**Comment by alxwr** [comment]
Made Timeout optional again in cc9d81c.

**Pull request merged**
