### PR TITLE
Improvements to the apache-formula

### PR DESCRIPTION
**Pull request by aboe76**
- Added more modules and configuration options
 - Renamed sls files to reflect what they do.
 - added mpm options for Debian

### CODE REVIEW

**Comment by puneetk** [comment]
Big changes, do you want to verbose up the pull request description ?

**Comment by aboe76** [comment]
Most of the changes, are only cosmetic, renaming of sls to mod_.sls
and are described in the Readme, But if you want I can elaborate on the pull request

**Comment by madssj** [comment]
@aboe76 the MPM switching only works on Debian 8+ and Apache 2.4. In Debian 7 and Apache <2.4 there's no switching MPM's dynamically. 

On Debian <8 they're separate packages, named `apache2-mpm-X` which all conflict with each other.

It should be fixed in the handling, or at least documented to be only working in Apache 2.4.

**Comment by madssj** [comment]
@aboe76 Oh yes, to make things even more complicated, in Debian <8 `libapache2-mod-php5` depends on `apache2-mpm-prefork`.

**Comment by aboe76** [comment]
@madssj you are right about debian 8+ and apache 2.4 that's what I was testing the formula against.
hadn't thought of backporting this to wheezy, can you create a Pull request on this? otherwise I need to spin up a wheezy machine...

**Comment by madssj** [comment]
@aboe76 I think it would take a pretty substantial rewrite to get the dependencies right. Spinning up a wheezy machine is a breeze these days, so you should do that regardless.

**Pull request merged**
