### PR TITLE
mod_mpm for RedHat

### PR DESCRIPTION
**Pull request by ardin**
**Summary of Changes**
- mpm configuration for RedHat os_family
- default: mpm_prefork with default configuration
  **Testing**
- Tested on CentOS

### CODE REVIEW

**Comment by gravyboat** [comment]
Were you able to confirm everything still works okay on Ubuntu/Debian?

**Comment by ardin** [comment]
I've tested only module on ubuntu:latest and it seems ok. In RedHat configuration i suppose pillar like:

<pre>
apache:
  mod_mpm_prefork:
    start_servers: 10
    max_request_workers: 10
    min_spare_servers: 10
    max_spare_servers: 20
    max_connections_per_child: 1000
</pre>

Debian/Ubuntu  configuration suppose pillar syntax:
<pre>
apache:
  mpm:
    params:
      start_servers: 10
      max_request_workers: 10
      min_spare_servers: 10
      max_spare_servers: 20
      max_connections_per_child: 1000
</pre>

Both are undocummented in pillar.example. My current approach is similar to other sls (like mod_security, mod_remoteip). Decide which approach is better please and don't accept request if you have diffrent opinion.

**Comment by aboe76** [comment]
@ardin can you add an example to the pillar.example file so it has some documentation?

**Comment by noelmcloughlin** [comment]
Fixed the conflict (caused by https://github.com/saltstack-formulas/apache-formula/pull/189).

**Pull request merged**
