### PR TITLE
let Directory_default actually use DocumentRoot if set, not always de…

### PR DESCRIPTION
**Pull request by nilsglow**
the standard.tmpl was not considering the DocumentRoot for the default Directory, but instead always used the default value `'{0}/{1}'.format(map.wwwdir, sitename)`

### CODE REVIEW

**Comment by gravyboat** [comment]
Hmm, are we going to create issues for anyone with this change?

**Comment by nilsglow** [comment]
True, some people may depend on the old behavior.

`DocumentRoot` and `Directory.default` both have the same default according to pillar.example, but of course that does not really imply, that `Directory.default` uses `DocumentRoot` if set. It is just what I assumed and then to me it seemed to be a bug...

I came across this because I have a site `www.example.com` with a `DocumentRoot` of `/var/www/example.com` and then the `Directory` entry was `/var/www/www.example.com` ...

But I agree, that the change would probably be bad for someone, so better don't merge!

**Comment by gravyboat** [comment]
I'm not saying we can't merge, just hoping we get some other people weighing in, let's leave this for a bit as I agree with your premise and reasoning for this PR.

**Comment by dexbleeker** [comment]
If I understand correctly, this only poses a problem for people that have set `DocumentRoot` and don't want to use it for their default directory options?

I however do think `pillar.example` should be updated in this pull request as well before merge.
(https://github.com/saltstack-formulas/apache-formula/blob/master/pillar.example#L75)

**Comment by noelmcloughlin** [comment]
Superseded by #231

**Pull request closed without merging**
