### PR TITLE
Remove duplicated ID (fixes #179), added minimal template (fixes #34)

### LINKED ISSUE #34: minimal.tmpl referenced in pillar.example not present in apache/vhosts/
title says it all

### LINKED ISSUE #179: apache.config and apache states have a conflicting ID
The vhost directory is defined as an ID in both apache/config.sls and apache/init.sls. This is invalid and causes a rendering exception when running the config state:

```
Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is '/etc/apache2/sites-available' and is found in SLS 'base:apache' and SLS 'base:apache.config'
```

### PR DESCRIPTION
**Pull request by javierbertoli**

### CODE REVIEW

**Comment by aboe76** [comment]
@javierbertoli why keep the vhostdir in the init.sls and not in the config.sls..?
I think config.sls is a better place...

**Comment by javierbertoli** [comment]
That was my 1st. idea too (keep the one in `config.sls` and remove the one in `init.sls`). but then I realized that `init.sls` is always included, while `config.sls` might not be. And other state files (ie `vhosts/standard.sls` requires the `{{ vhostdir }}` resource. Keeping the `config.sls` file one would make it a requirement when you just wanted to configure some vhosts, keeping all the default configuration.

What do you think? I'm open to change it, if you prefer the other location.

**Comment by aboe76** [comment]
I find it strange that you want to configure vhosts but not the config.sls because envvars and ports are done 
with config.sls... but then again this formula is getting a bit on the strange site, with debian_full.sls and register_site hardcoded path's...

**Comment by javierbertoli** [comment]
Well, I moved it `init.sls` because I considered you could configure vhosts without modifying the 'general' config (envvars, ports, etc). But I agree with you on the messiness of the formula, so I moved it back to `config` again, so we can try to get things a bit more organized 😄

**Comment by aboe76** [comment]
Let's merge this and see if it can be cleaned a bit some pr's are waiting too long ...

**Pull request merged**
