### PR TITLE
multiple commits for rhel (7), use watch module: apache-[restart|reload] consequently, make Listen more modular, mod_ssl for rhel, server-status state(for clusters like Pacemaker)

### PR DESCRIPTION
**Pull request by hoonetorg**
**Summary of Changes**
- Issue summary:
  - multiple commits for rhel (7) 
  - use watch module: apache-[restart|reload] consequently
  - make Listen more modular 
  - mod_ssl for rhel
  - server-status state(for clusters like Pacemaker)
  - pcs state for creating Pacemaker cluster resources with PCS.
  - make service more modular (allow it to be disabled if apache is manageg by clusters like Pacemaker)
  - defaults.yaml
  - orchestration state to deploy apache on a pacemaker cluster (requires salt pcs module and state-module from salt development branch)

**Testing**
- Tested on OS 

Changes should all be backward compatible.

### CODE REVIEW

**Comment by hoonetorg** [comment]
added a cluster pillar example

**Comment by gravyboat** [comment]
Woah this is an old commit, not sure how it got missed. Can you rebase then we can review it?

**Comment by hoonetorg** [comment]
hi sorry, did not uncomment the hook
give me some time, must finish my master thesis first

**Comment by aboe76** [comment]
@hoonetorg do you have some time now?

**Pull request closed without merging**
