### PR TITLE
Feature/remote ip internal proxy support

### PR DESCRIPTION
**Pull request by mariusvw**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Nearly there ;-)  The linters want lower-case commit message:  `" subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]"`.  Easiest way is git rebase: see https://wideopentech.com/how-do-i-amend-multiple-commits-with-git/ and change uppercases to lower.

**Comment by myii** [comment]
Perhaps it would be simpler to just amend the commit message using the `Squash and merge` button?  The second commit isn't significant, so we could just have the one squashed commit:

```
feat(trusted_proxy): add support for RemoteIPInternalProxy
```

**Comment by noelmcloughlin** [comment]
> `Squash and merge` button?

Interesting. Where is that button?  I cannot see it..

image

**Comment by myii** [comment]
> Interesting. Where is that button? I cannot see it..

@noelmcloughlin It's one of the drop-down options of the `Merge pull request` button.  Note, that GitHub will remember your setting for this formula, so when you next merge a PR here, it will probably still be set to `Squash and merge`!

You can override the commit message in the textbox at the top, which probably has `Feature/remote ip internal proxy support (#300)` in it by default.

**Comment by noelmcloughlin** [comment]
Thanks @myii  learned something new.  Thanks, @mariusvw  for the PR and improvements!!!  Appreciated.

**Comment by noelmcloughlin** [comment]
The only issue with "squash and merge" is that PR gets merged immediately by me (no CI job).  
However, if @mariusvw uses git rebase/squash/reword then a new commit is created and Travis CI jobs will rerun.

**Comment by noelmcloughlin** [comment]
anyway its merged ;-)

**Comment by myii** [comment]
> The only issue with "squash and merge" is that PR gets merged immediately by me (no CI job).
> However, if @mariusvw uses git rebase/squash/reword then a new commit is created and Travis CI jobs will rerun.

Yep, I should have mentioned that.  If I'm concerned about the PR before the squash and merge, I run it in my own fork first.

**Comment by mariusvw** [comment]
@noelmcloughlin / @myii, I'll use the [semantic-release](https://github.com/semantic-release/semantic-release) next time, no problem, I'd rather learn than someone else silently fixing it ;)

**Pull request merged**
