### PR TITLE
Configure listen directive

### LINKED ISSUE #33: ability to configure listening ports
Missing the ability to control the 'Listen' directives. On Debian 14.04, that is configured with the file /etc/apache2/ports.conf

### PR DESCRIPTION
**Pull request by genuss**
Add listen directive to vhosts templates and remove ports.conf
This should also fix #33

### CODE REVIEW

**Comment by gravyboat** [comment]
Thanks.

**Comment by gravyboat** [comment]
Thanks for pointing that out @jeffrysleddens, I hadn't considered that. @genuss do you want to see if you can introduce a patch? Or @jeffrysleddens if you're feeling up to it.

**Comment by genuss** [comment]
So you mean if you use salt only to install apache package but you don't use ``apache.vhosts`` state?
But how is that possible?

**Comment by jeffrysleddens** [comment]
Indeed we don't use the apache.vhosts state.

We only use the apache.debian_full state

Our state init.sls looks like this:

include:
  - apache.debian_full



And our pillar init.sls looks like this:

apache:
  wwwdir: /srv/www
  register-site:
    autodiscover:
      name: autodiscover
      path:
salt://servers/server_name/files/etc/apache2/sites-available/autodiscover.conf
      state: enabled
    examportal:
      name: examportal
      path:
salt://servers/server_name/files/etc/apache2/sites-available/examportal.conf
      state: enabled
    ... etc ...



This used to work perfectly. But now this state is broken because of the
missing ports.conf.

One solution/workaround I can think of is making it configurable in the
pillar whether to use the site wide ports.conf or not.

Or we could surround the file.absent block in debian_full.sls with a check
for the existance of the sites pillar:

{% if pillar['apache.sites'] is defined %}
/etc/apache2/ports.conf:
  file.absent:
    - require:
      - pkg: apache
{% endif %}

**Comment by genuss** [comment]
@jeffrysleddens, look at #113 please.

**Pull request merged**
